#!/bin/bash

typeset -i days

# ---

comm="chart-sar-data-all-cols"

# ---

if [ "$(which ${comm})" = "" ]
then
        this_dir="$(dirname $(which $0) )"
        if [ "${this_dir}" != "" ]
        then
                echo "Info: Adding '${this_dir}' to PATH to make '${comm}' script available."
                export PATH="${PATH}:${this_dir}"
        fi
fi

# ---

days=$1

if [ ${days} -lt 1 ]
then
	days=3
fi

# ---

sar_opts="-R"
chart_title="Memory Stats"
output="/tmp/sar/$(hostname)-sar-mem-stats.html"

# ---

echo "Writing SVG charts to file '${output}'"

"${comm}" "${sar_opts}" "${chart_title}" ${days} "${output}"

# ---

exit $?
		
