#!/bin/bash

typeset -i days col low high

# ---

comm="chart-sar-generic"

# ---

if [ "$(which ${comm})" = "" ]
then
        this_dir="$(dirname $(which $0) )"
        if [ "${this_dir}" != "" ]
        then
                echo "Info: Adding '${this_dir}' to PATH to make '${comm}' script available."
                export PATH="${PATH}:${this_dir}"
        fi
fi

# ---

sar_opts="$1"
chart_title="$2"
days="$3"
output="$4"

if [ "${sar_opts}" = "" ]
then
	echo "Error: Options to be passed to 'sar' command not provided on command line"
	echo "Syntax is $0 'sar-command-options' [ 'chart-title' [ #days ] ]"
	exit 1
fi

# ---

if [ ${days} -lt 1 ]
then
	days=3
fi


# ---

crange=( $(sar ${sar_opts} 1 1 \
    | gawk '

	NF && $NF != "CPU)" \
	{
		headcheck = $NF
		gsub("[0-9.-]", "", headcheck)
		if( headcheck == "" )
		{
			low = high = NF

			for( col = 3; col <= NF && low == NF; col++ )
			{
				gsub("[0-9.-]", "", $col)
				if( $col == "" ) low = col
			}

			printf "%d %d\n", low, high
			exit(0)
		}
	}' \
    )
)

low=${crange[0]}
high=${crange[1]}

# ---

col=${low}

if [ "${output}" ]
then
	rm "${output}" 2>/dev/null
fi

while [ ${col} -le ${high} ]
do
	echo "Run column ${col} of ${high}"

	if [ "${output}" != "" ]
	then
		"${comm}" ${days} "${sar_opts}" ${col} "${chart_title}" >>"${output}"
	else
		"${comm}" ${days} "${sar_opts}" ${col} "${chart_title}"
	fi

	col=$(( ${col} + 1 ))
done

# ---

exit $?
		
