#!/bin/bash

typeset -i days col low high

# ---

comm="chart-sar-generic"

# ---

if [ "$(which ${comm})" = "" ]
then
        this_dir="$(dirname $(which $0) )"
        if [ "${this_dir}" != "" ]
        then
                echo "Info: Adding '${this_dir}' to PATH to make '${comm}' script available."
                export PATH="${PATH}:${this_dir}"
        fi
fi

# ---

sar_opts="-n DEV"
chart_title="Network Device Stats"

title_pref=" ("
title_suff=")"

out_dir="/tmp/sar/"
out_pref="${out_dir}$(hostname)-sar-net-dev-"
out_suff=".html"

# ---

if [ ! -d "${out_dir}" ]
then
	mkdir "${out_dir}"
fi

# ---

days="$1"

if [ ${days} -lt 1 ]
then
	days=3
fi

dev="$2"

if [ "${dev}" = "" ]
then
	dev="$(sar ${sar_opts} 1 1 \
	    | gawk '
		$1 == "Average:" && $2 != "IFACE" \
		{
		    if( use == "" ) use = $2
		    else if( $2 != "lo" )
		    {
			if( substr(use, 1, 3) == "tun" ) use = $2
		    }
		}

		END \
		{
		    printf "%s", use
		}'
	)"

	if [ "${dev}" = "" ]
	then
		echo "Error: Can't figure out what device to use."
		exit 1
	fi

	echo "No device specified, will use '${dev}'"
fi

output="${out_pref}${dev}${out_suff}"
chart_title="${chart_title}${title_pref}${dev}${title_suff}"

# ---

crange=( $(sar ${sar_opts} 1 1 \
    | gawk '

	NF && $NF != "CPU)" \
	{
		headcheck = $NF
		gsub("[0-9.-]", "", headcheck)
		if( headcheck == "" )
		{
			low = high = NF

			for( col = 3; col <= NF && low == NF; col++ )
			{
				gsub("[0-9.-]", "", $col)
				if( $col == "" ) low = col
			}

			printf "%d %d\n", low, high
			exit(0)
		}
	}' \
    )
)

low=${crange[0]}
high=${crange[1]}

# ---

col=${low}

echo "Creating chart '${output}'"
cat /dev/null >"${output}"

while [ ${col} -le ${high} ]
do
	echo "Run column ${col} of ${high}"

	"${comm}" ${days} "${sar_opts}" ${col} "${chart_title}" "" " ${dev} " >>"${output}"

	col=$(( ${col} + 1 ))
done

# ---

exit $?
		
